// generated by stringer -type=HTTPMethod; DO NOT EDIT

package parser

import "fmt"

const _HTTPMethod_name = "UNKNOWN_HTTP_METHODGETPOSTPUTDELETE"

var _HTTPMethod_index = [...]uint8{0, 19, 22, 26, 29, 35}

func (i HTTPMethod) String() string {
	if i < 0 || i >= HTTPMethod(len(_HTTPMethod_index)-1) {
		return fmt.Sprintf("HTTPMethod(%d)", i)
	}
	return _HTTPMethod_name[_HTTPMethod_index[i]:_HTTPMethod_index[i+1]]
}
