package parser

import "fmt"

// This is temporal until the issue https://github.com/golang/go/issues/13744 gets solved
// This should be autogenerated

func HTTPMethodString(s string) (HTTPMethod, error) {
	switch s {
	case GET.String():
		return GET, nil
	case POST.String():
		return POST, nil
	case PUT.String():
		return PUT, nil
	case DELETE.String():
		return DELETE, nil
	default:
		return 0, fmt.Errorf("%s does not belong to HTTPMethod values", s)
	}
}
